version: "3"

services:
  svelte:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: "${COMPOSE_PROJECT_NAME}_PROJECT"
    restart: always
    ports:
      - "4160:4160"
    command:
      "npm run preview"


  nginx:
    image: nginx:1.13
    container_name: "${COMPOSE_PROJECT_NAME}_NGINX"
    ports:
      - "1116:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - svelte
